#!/usr/bin/env python3
"""
Configure, build, and upload the Guarda-Rios ESP32 station firmware.

The current binary ingest protocol sends a numeric station_id, not a text
station name. This tool still asks for a human station name so it can derive
a stable station_id when one is not supplied explicitly.
"""

from __future__ import annotations

import argparse
import binascii
import getpass
import glob
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SKETCH = REPO_ROOT / "PGR_Station" / "PGR_Station.ino"
DEFAULT_FQBN = "esp32:esp32:esp32"


def prompt(text: str, default: str | None = None, secret: bool = False) -> str:
    suffix = f" [{default}]" if default else ""
    while True:
        if secret:
            value = getpass.getpass(f"{text}{suffix}: ")
        else:
            value = input(f"{text}{suffix}: ")
        value = value.strip()
        if value:
            return value
        if default is not None:
            return default


def prompt_int(text: str, default: int, maximum: int | None = None) -> int:
    while True:
        raw_value = prompt(text, str(default))
        try:
            return positive_int(raw_value, text.lower(), maximum)
        except argparse.ArgumentTypeError as exc:
            print(f"error: {exc}", file=sys.stderr)


def station_id_from_name(name: str) -> int:
    value = binascii.crc_hqx(name.encode("utf-8"), 0xFFFF) & 0xFFFF
    return value if value != 0 else 1


def positive_int(value: str, name: str, maximum: int | None = None) -> int:
    try:
        parsed = int(value, 10)
    except ValueError:
        raise argparse.ArgumentTypeError(f"{name} must be an integer") from None

    if parsed <= 0:
        raise argparse.ArgumentTypeError(f"{name} must be greater than zero")
    if maximum is not None and parsed > maximum:
        raise argparse.ArgumentTypeError(f"{name} must be <= {maximum}")
    return parsed


def bounded_int(value: str, name: str, minimum: int, maximum: int) -> int:
    try:
        parsed = int(value, 10)
    except ValueError:
        raise argparse.ArgumentTypeError(f"{name} must be an integer") from None

    if parsed < minimum or parsed > maximum:
        raise argparse.ArgumentTypeError(f"{name} must be between {minimum} and {maximum}")
    return parsed


def station_id_arg(value: str) -> int:
    return positive_int(value, "station id", 65535)


def interval_arg(value: str) -> int:
    return positive_int(value, "send interval", 65535)


def sample_count_arg(value: str) -> int:
    return positive_int(value, "sample count", 255)


def timestamp_offset_arg(value: str) -> int:
    return bounded_int(value, "timestamp offset", -86400, 86400)


def list_serial_ports() -> list[str]:
    candidates: list[str] = []
    patterns = [
        "/dev/ttyUSB*",
        "/dev/ttyACM*",
        "/dev/cu.usbserial*",
        "/dev/cu.usbmodem*",
        "COM*",
    ]
    for pattern in patterns:
        candidates.extend(glob.glob(pattern))
    return sorted(set(candidates))


def replace_const(source: str, c_type: str, name: str, value: int) -> str:
    pattern = rf"static const {re.escape(c_type)} {re.escape(name)} = -?\d+;"
    replacement = f"static const {c_type} {name} = {value};"
    patched, count = re.subn(pattern, replacement, source, count=1)
    if count != 1:
        raise RuntimeError(f"could not patch {name} in sketch")
    return patched


def write_configured_sketch(
    sketch_path: Path,
    build_root: Path,
    station_id: int,
    send_interval_s: int,
    sample_count: int,
    timestamp_offset_s: int,
    station_token: str,
) -> Path:
    sketch_source = sketch_path.read_text(encoding="utf-8")
    sketch_source = replace_const(sketch_source, "uint16_t", "STATION_ID", station_id)
    sketch_source = replace_const(sketch_source, "uint16_t", "SAMPLE_INTERVAL_S", send_interval_s)
    sketch_source = replace_const(sketch_source, "uint8_t", "SAMPLE_COUNT", sample_count)
    sketch_source = replace_const(sketch_source, "int32_t", "TIMESTAMP_OFFSET_S", timestamp_offset_s)

    configured_dir = build_root / sketch_path.stem
    configured_dir.mkdir(parents=True, exist_ok=True)
    configured_sketch = configured_dir / f"{sketch_path.stem}.ino"
    configured_sketch.write_text(sketch_source, encoding="utf-8")

    escaped_token = station_token.replace("\\", "\\\\").replace('"', '\\"')
    (configured_dir / "station_secrets.h").write_text(
        "#pragma once\n\n"
        "/* Generated by ESP32_Flasher/flash_station.py. */\n"
        f'#define STATION_TOKEN "{escaped_token}"\n',
        encoding="utf-8",
    )
    return configured_dir


def run(command: list[str], dry_run: bool = False) -> None:
    print("+ " + " ".join(command))
    if dry_run:
        return
    subprocess.run(command, check=True)


def ensure_arduino_cli() -> str:
    arduino_cli = shutil.which("arduino-cli")
    if arduino_cli is None:
        raise RuntimeError(
            "arduino-cli was not found on PATH. Install it and the ESP32 core, then rerun this tool."
        )
    return arduino_cli


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Configure and upload the Guarda-Rios ESP32 station firmware."
    )
    parser.add_argument("--port", help="ESP32 serial port, for example /dev/ttyUSB0 or COM3")
    parser.add_argument("--fqbn", default=DEFAULT_FQBN, help=f"Arduino board FQBN (default: {DEFAULT_FQBN})")
    parser.add_argument("--sketch", type=Path, default=DEFAULT_SKETCH, help="source station .ino file")
    parser.add_argument("--station-name", help="human station name used to derive a station id if needed")
    parser.add_argument("--station-id", type=station_id_arg, help="numeric id sent to the server (1-65535)")
    parser.add_argument("--station-token", help="shared HMAC token configured on the server")
    parser.add_argument(
        "--send-interval",
        type=interval_arg,
        help="ESP32 deep-sleep interval; packets are sent every interval when sample-count is 1",
    )
    parser.add_argument(
        "--sample-count",
        type=sample_count_arg,
        default=1,
        help="samples retained across deep sleeps per packet; use 1 to send each wake (default: 1)",
    )
    parser.add_argument(
        "--timestamp-offset",
        type=timestamp_offset_arg,
        default=0,
        help="seconds added to modem timestamps before sending (default: 0)",
    )
    parser.add_argument("--compile-only", action="store_true", help="build but do not upload")
    parser.add_argument("--dry-run", action="store_true", help="show commands without running arduino-cli")
    parser.add_argument(
        "--keep-build-dir",
        action="store_true",
        help="keep the temporary configured sketch directory after the run",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    sketch_path = args.sketch.resolve()
    if not sketch_path.exists():
        print(f"error: sketch not found: {sketch_path}", file=sys.stderr)
        return 2

    station_name = args.station_name
    if station_name is None:
        station_name = prompt("Station name")

    station_id = args.station_id
    if station_id is None:
        derived_id = station_id_from_name(station_name)
        station_id = prompt_int("Station numeric id sent to server", derived_id, 65535)

    station_token = args.station_token
    if station_token is None:
        station_token = prompt("Station token/shared key", secret=True)

    send_interval = args.send_interval
    if send_interval is None:
        send_interval = prompt_int("Send interval in seconds", 300, 65535)

    port = args.port
    if port is None and not args.compile_only:
        ports = list_serial_ports()
        if ports:
            print("Detected serial ports: " + ", ".join(ports))
        port = prompt("ESP32 serial port", ports[0] if ports else None)

    print()
    print(f"Station name: {station_name}")
    print(f"Station id sent to server: {station_id}")
    print(f"Sample interval: {send_interval} s")
    print(f"Samples per packet: {args.sample_count}")
    print(f"Timestamp offset: {args.timestamp_offset} s")
    print(f"ESP32 deep-sleep interval: {send_interval} s")
    print(f"Approximate packet send cadence: {send_interval * args.sample_count} s")
    print()

    if not args.dry_run:
        arduino_cli = ensure_arduino_cli()
    else:
        arduino_cli = "arduino-cli"

    temp_dir = Path(tempfile.mkdtemp(prefix="pgr_station_"))
    try:
        configured_sketch_dir = write_configured_sketch(
            sketch_path,
            temp_dir,
            station_id,
            send_interval,
            args.sample_count,
            args.timestamp_offset,
            station_token,
        )

        run(
            [
                arduino_cli,
                "compile",
                "--fqbn",
                args.fqbn,
                str(configured_sketch_dir),
            ],
            dry_run=args.dry_run,
        )

        if not args.compile_only:
            run(
                [
                    arduino_cli,
                    "upload",
                    "-p",
                    port,
                    "--fqbn",
                    args.fqbn,
                    str(configured_sketch_dir),
                ],
                dry_run=args.dry_run,
            )
    finally:
        if args.keep_build_dir:
            print(f"Configured sketch kept at: {temp_dir}")
        else:
            shutil.rmtree(temp_dir, ignore_errors=True)

    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except subprocess.CalledProcessError as exc:
        raise SystemExit(exc.returncode) from exc
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc
